export const HERO_CHIPS = ["hot dog", "cereal", "pop-tart", "lasagna", "pizza"] as const;

export const SURPRISE_FOODS = [
  "hot dog",
  "cereal",
  "pop-tart",
  "lasagna",
  "pizza",
  "burrito",
  "sushi burrito",
  "taco salad",
  "ice cream sandwich",
  "cheesecake",
  "club sandwich",
  "folded quesadilla",
  "gyro",
  "crunchwrap",
  "spring roll",
  "s'more",
  "bao",
  "tostada",
  "burrito bowl",
  "onigiri",
  "ramen",
  "poutine",
  "pigs in a blanket",
  "empanada",
  "pierogi",
  "cannoli",
  "eclair",
  "croissant",
  "bagel",
  "stack of pancakes",
  "french toast",
  "grilled cheese",
  "lobster roll",
  "samosa",
  "apple pie",
  "slice of apple pie",
  "cupcake",
  "muffin",
  "twinkie",
  "oreo",
  "pad thai",
  "fried rice",
  "mac and cheese",
  "chili",
  "soup in a bread bowl",
  "sloppy joe",
  "big mac",
  "tamale",
  "corn dog",
  "hot pocket",
  "ice cream cone",
  "bubble tea",
  "chicken pot pie",
  "shepherd's pie",
  "baklava",
  "stuffed crust pizza",
  "deep dish pizza",
  "egg roll",
  "wonton soup",
  "croque monsieur",
] as const;

export function surpriseFood(current: string | null, random = Math.random): string {
  const pool = SURPRISE_FOODS.filter((food) => food !== current);
  return pool[Math.floor(random() * pool.length)] ?? "hot dog";
}
